environment:
  nodejs_version: "6"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
before_test:
  - node --version
  - npm --version
test_script:
  - npm run artillery-test
  - npm test
build: off