image:
  - Visual Studio 2017
environment:
  nodejs_version: "6"
cache:
  - node_modules 
  - bower_components
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
before_test:
  - tsc -v
  - tsc
test_script:
  - node --version
  - npm --version
  - npm test
build: off