image:
  - Visual Studio 2017
environment:
  nodejs_version: "6"
cache:
  - node_modules 
  - bower_components
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install typescript -g
  - npm install grunt-cli -g
configuration: Release
before_test:
  - tsc
  - grunt
test_script:
  - tsc -v
  - node --version
  - npm --version
  - npm test
after_build:
  - npm version %APPVEYOR_BUILD_VERSION% -m 'v%APPVEYOR_BUILD_VERSION%'
build: off