// Generated by CoffeeScript 1.12.7
(function() {
  var database, express, item, router;

  express = require('express');

  router = express.Router();

  database = require('../routes/database');

  item = require('../routes/item');

  router.post('/:method', function(req, res, next) {
    var collection, db;
    db = database.getDb();
    if (req.params.method === 'new') {
      console.log('new');
      collection = new item.collection(database.getId(), req.body.Name, req.body.Status, req.body.Type, req.body.Link, req.body.Description, req.body.Date, req.body.Technologies, req.body.Images);
      db.collection('collection').insert(collection);
      db.collection('collection').find({}).toArray(function(err, result) {
        return console.log(result);
      });
    }
  });

  router.get('/', function(req, res, next) {
    database.getDb().collection('collection').find({}).toArray(function(err, result) {
      res.render('collectiondata', {
        itemKeys: Object.keys(result),
        items: result
      });
    });
  });

  module.exports = router;

}).call(this);
