// Generated by CoffeeScript 1.12.7
(function() {
  var baseItem, collection, item, team,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  baseItem = (function() {
    function baseItem(_id, name, status, type, link) {
      this._id = _id;
      this.name = name;
      this.status = status;
      this.type = type;
      this.link = link;
    }

    return baseItem;

  })();

  item = (function(superClass) {
    extend(item, superClass);

    function item() {
      return item.__super__.constructor.apply(this, arguments);
    }

    item.prototype.setCollection = function(collection) {
      collection.addItem(this._id);
      this.collection = collection._id;
    };

    return item;

  })(baseItem);

  collection = (function(superClass) {
    extend(collection, superClass);

    function collection(_id, name, status, type, link) {
      this._id = _id;
      this.name = name;
      this.status = status;
      this.type = type;
      this.link = link;
      collection.__super__.constructor.call(this, this._id, this.name, this.status, this.type, this.link);
      this.childrens = [];
    }

    collection.prototype.addItem = function(items) {
      this.childrens.push(items);
    };

    return collection;

  })(baseItem);

  team = (function() {
    function team(name, logo, members1, site) {
      this.name = name;
      this.logo = logo;
      this.members = members1;
      this.site = site;
    }

    team.prototype.addMember = function(members) {
      var i, len, member;
      if (typeof (members === 'object')) {
        for (i = 0, len = members.length; i < len; i++) {
          member = members[i];
          this.members.push(member);
        }
      } else {
        this.members.push(member);
      }
    };

    return team;

  })();

  module.exports = {
    item: item,
    collection: collection
  };

}).call(this);
