// Generated by CoffeeScript 1.12.7
(function() {
  var database, express, item, router;

  express = require('express');

  router = express.Router();

  database = require('../routes/database');

  item = require('../routes/item');

  router.get('/', function(req, res, next) {
    return database.getDb().collection('team').find({}).toArray(function(err, teams) {
      return database.getDb().collection('collection').find({}).toArray(function(err, collections) {
        return database.getDb().collection('item').find({}).toArray(function(err, items) {
          return res.render('teamdata', {
            teamKeys: Object.keys(teams),
            teams: teams,
            collectionKeys: Object.keys(collections),
            collections: collections,
            itemKeys: Object.keys(items),
            items: items
          });
        });
      });
    });
  });

  module.exports = router;

}).call(this);
